// src/app/layout.

import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'; // Import your global CSS
import NavbarPage from './navbar/page';
import ContactUs from './contactus/page';
import Footer  from './footer/page';


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'BytiBits',
  description: 'Generated by Namoos Ahmed',
  
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="row "  style={{width:'95%',  margin:'0 auto', padding:'0'}}>  
      <NavbarPage />
      </div>
      {children}
<div  style={{marginTop:'-15%'}}>

      


<ContactUs />
</div>

<div style={{marginTop:'-15%'}} >
<Footer />
</div>
      </body>
  
    </html>
  );
}
